logging.level:
  nc.unc.gl.borne: debug

spring.mustache.check-template-location: false

# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.whitelisted-packages: unc.gl
